-- ==========================================
-- 装备造价历史记录与价格数据库初始化脚本
-- ==========================================

-- 1. 创建造价历史记录表
CREATE TABLE IF NOT EXISTS public.crafting_history (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamptz DEFAULT now(),
    equipment_id text, -- 装备 ID
    equipment_name text NOT NULL, -- 装备名称
    kinah_rate numeric DEFAULT 0, -- 1元 = 多少万基纳
    total_kinah numeric DEFAULT 0, -- 实际所需总基纳
    total_rmb numeric DEFAULT 0, -- 预估人民币
    materials_data jsonb NOT NULL, -- 存储当时的材料明细: [{id, name, price_w, quantity, owned, missing}]
    user_id uuid DEFAULT auth.uid() -- 记录执行计算的用户(如果有登录)
);

-- 2. 开启 RLS
ALTER TABLE public.crafting_history ENABLE ROW LEVEL SECURITY;

-- 3. 配置 RLS 策略
-- 允许所有人查看历史记录 (如果需要公开透明)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read for crafting_history') THEN
        CREATE POLICY "Allow public read for crafting_history" ON public.crafting_history FOR SELECT USING (true);
    END IF;

    -- 允许任何已登录用户或匿名用户(如果允许匿名记录) 插入记录
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow insert for crafting_history') THEN
        CREATE POLICY "Allow insert for crafting_history" ON public.crafting_history FOR INSERT WITH CHECK (true);
    END IF;

    -- 仅允许管理员删除历史记录
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow admin delete crafting_history') THEN
        CREATE POLICY "Allow admin delete crafting_history" ON public.crafting_history FOR DELETE USING (auth.role() = 'authenticated');
    END IF;
END $$;

-- 4. 在 site_config 中初始化一个用于快速查询“近期价格”的 key (可选，也可通过 SQL 直接从历史表查)
INSERT INTO public.site_config (key, value)
VALUES ('material_recent_prices', '{}')
ON CONFLICT (key) DO NOTHING;
