-- 创建军团成员表
create table if not exists public.legion_members (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  character_id text not null unique,
  name text not null,
  server_id bigint,
  race_id smallint,
  level integer,
  class_name text,
  profile_url text,
  role text default 'member'::text, -- member, officer, leader
  join_date timestamp with time zone,
  note text
);

-- 开启 RLS (行级安全)
alter table public.legion_members enable row level security;

-- 创建策略：允许所有人读取（用于首页展示）
create policy "Enable read access for all users" 
on public.legion_members for select 
using (true);

-- 创建策略：仅允许认证用户进行增删改（用于后台管理）
create policy "Enable insert for authenticated users only" 
on public.legion_members for insert 
with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only" 
on public.legion_members for update 
using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only" 
on public.legion_members for delete 
using (auth.role() = 'authenticated');
