-- ==========================================
-- 装备造价计算器数据库初始化脚本
-- ==========================================

-- 1. 确保 site_config 表存在 (如果之前没有创建过)
CREATE TABLE IF NOT EXISTS public.site_config (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    key text UNIQUE NOT NULL,
    value jsonb NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 2. 开启 RLS
ALTER TABLE public.site_config ENABLE ROW LEVEL SECURITY;

-- 3. 创建 RLS 策略 (如果不存在)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read for site_config') THEN
        CREATE POLICY "Allow public read for site_config" ON public.site_config FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow auth update for site_config') THEN
        CREATE POLICY "Allow auth update for site_config" ON public.site_config FOR ALL USING (auth.role() = 'authenticated');
    END IF;
END $$;

-- 4. 初始化装备造价配置 (如果不存在)
INSERT INTO public.site_config (key, value)
VALUES (
    'equipment_cost_config', 
    '{
        "materials": [
            {"id": "13", "name": "达人最上級提炼石"},
            {"id": "15", "name": "愤怒思念"},
            {"id": "16", "name": "灿烂的奧里哈康石"},
            {"id": "17", "name": "灿烂的奧德"},
            {"id": "19", "name": "愤怒意志"},
            {"id": "21", "name": "愤怒自我"},
            {"id": "22", "name": "提炼的強固龙族角"},
            {"id": "23", "name": "发狂的愤怒巫蠱"},
            {"id": "26", "name": "达人闪耀的奧里哈康长剑"}
        ],
        "equipment": [
            {
                "id": "e1_kuilong",
                "name": "夔龙王长剑",
                "category": "武器",
                "materials": [
                    { "materialId": "13", "count": 50 },
                    { "materialId": "15", "count": 18 },
                    { "materialId": "16", "count": 121 },
                    { "materialId": "17", "count": 70 },
                    { "materialId": "19", "count": 27 },
                    { "materialId": "21", "count": 42 },
                    { "materialId": "22", "count": 122 },
                    { "materialId": "23", "count": 19 },
                    { "materialId": "26", "count": 5 }
                ]
            }
        ]
    }'
)
ON CONFLICT (key) DO NOTHING;

-- 5. 确保首页 Tab 配置包含 "造价计算" (可选手动更新，也可通过此脚本)
-- 注意：这里会尝试更新已有的 home_tabs 配置，添加 cost 页签
DO $$
DECLARE
    current_tabs jsonb;
BEGIN
    SELECT value INTO current_tabs FROM public.site_config WHERE key = 'home_tabs';
    
    IF current_tabs IS NOT NULL AND NOT (current_tabs @> '[{"id": "cost"}]') THEN
        UPDATE public.site_config 
        SET value = current_tabs || '[{"id": "cost", "name": "造价计算", "hidden": false}]'
        WHERE key = 'home_tabs';
    END IF;
END $$;
