-- ==========================================
-- 装备造价：材料单价波动历史表
-- ==========================================

-- 1. 创建材料价格波动历史表
CREATE TABLE IF NOT EXISTS public.material_price_history (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamptz DEFAULT now(),
    material_id text NOT NULL, -- 材料的 ID
    material_name text NOT NULL, -- 材料的名称
    price_w numeric NOT NULL, -- 当时的单价(万基纳)
    calculation_id int8 -- 关联的计算历史 ID
);

-- 2. 为查询加速：建立索引
CREATE INDEX IF NOT EXISTS idx_material_price_history_material_id ON public.material_price_history (material_id);
CREATE INDEX IF NOT EXISTS idx_material_price_history_created_at ON public.material_price_history (created_at);

-- 3. 开启 RLS
ALTER TABLE public.material_price_history ENABLE ROW LEVEL SECURITY;

-- 4. 配置 RLS 策略
-- 允许所有人查看材料价格历史 (用于折线图)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read for material_price_history') THEN
        CREATE POLICY "Allow public read for material_price_history" ON public.material_price_history FOR SELECT USING (true);
    END IF;

    -- 允许系统写入价格数据
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow system insert for material_price_history') THEN
        CREATE POLICY "Allow system insert for material_price_history" ON public.material_price_history FOR INSERT WITH CHECK (true);
    END IF;
END $$;
